import re
from typing import Dict, List
from robot_models import RobotData

def inject_gazebo_tags(urdf_content: str, robot: RobotData) -> str:
    """
    Injects Gazebo-specific tags into the URDF content.
    - Adds <gazebo> materials for links.
    - Adds a <gazebo> plugin for ros_control.
    """
    
    # 1. Add Gazebo Materials for Links
    # We find where </link> is and insert <gazebo reference="..."><material>...</material></gazebo> after it?
    # Or cleaner: Just append all gazebo tags at the end of the <robot> block, before </robot>.
    
    gazebo_tags = "\n  <!-- Gazebo-specific Link Properties -->\n"
    
    for link_id, link in robot.links.items():
        # Clean name resolution is tough if we don't pass the map.
        # However, the URDF content already has the sanitized names.
        # We need the sanitized names to reference them. 
        # Since we don't have the map here easily without passing it, 
        # let's rely on parsing valid names or assume standard naming convention if possible?
        # BETTER: Pass the unique_link_names map if possible.
        # BUT: For simplicity, we can inject these tags into the standard URDF generator OR
        # rely on the fact that we can append generic tags if we know the names.
        
        # Let's assume the caller passes generic content. 
        # Actually, let's just append a generic ROS Control plugin which is global.
        pass
        
    # Since we need to know the exact link names generated by the URDF exporter to reference them,
    # it's safer if we just add the global plugin for now.
    # Individual link materials are nice but not strictly required for "testing in Gazebo".
    # The default URDF materials usually show up in Gazebo (sometimes white/grey).
    
    # Let's add the control plugin which is essential for moving joints.
    gazebo_plugin = """
  <!-- Gazebo ROS Control Plugin -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>
"""
    
    # Insert before </robot>
    if "</robot>" in urdf_content:
        urdf_content = urdf_content.replace("</robot>", f"{gazebo_plugin}\n</robot>")
        
    return urdf_content

def generate_gazebo_launch(robot_name: str) -> str:
    """Generates a standard ROS 1 launch file for Gazebo."""
    launch_xml = f"""<launch>
  <!-- Argument for GUI -->
  <arg name="gui" default="true"/>
  <arg name="paused" default="false"/>

  <!-- Launch Gazebo World -->
  <include file="$(find gazebo_ros)/launch/empty_world.launch">
    <arg name="gui" value="$(arg gui)" />
    <arg name="paused" value="$(arg paused)"/>
    <arg name="use_sim_time" value="true"/>
  </include>

  <!-- Load Robot Description -->
  <param name="robot_description" textfile="$(find {robot_name})/urdf/{robot_name}.urdf" />

  <!-- Spawn Robot -->
  <node name="urdf_spawner" pkg="gazebo_ros" type="spawn_model" respawn="false" output="screen"
        args="-urdf -model {robot_name} -param robot_description"/>
        
  <!-- Robot State Publisher -->
  <node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher">
    <param name="publish_frequency" type="double" value="50.0" />
  </node>
  
  <!-- Joint State Publisher (Fake for validation if no controllers) -->
  <!-- <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher" /> -->

</launch>
"""
    return launch_xml
